// GENERATED by Scripts/generate-version.sh — do not edit, and do not commit a
// stamped value. The release build overwrites this from the tag; the committed
// value is the dev fallback a plain `swift build` reports.
enum GeneratedVersion {
    static let value = "0.0.0-dev"
}
