#!/usr/bin/env bash
# Write Sources/RheoclesCore/Version.generated.swift from a version string, so
# the daemon reports the version it was BUILT as — on GET /, in every manifest,
# and from --version — rather than a hand-typed constant that drifts from
# Info.plist (which is exactly how a notarized 0.1.1 shipped a daemon still
# saying 0.1.0). Called by bundle.sh and by the release workflow's Version step.
#
# The argument is the version (a leading "v" is stripped). With none, it writes
# the 0.0.0-dev fallback — the value a plain `swift build` reports and the value
# checked into the repo, so the two are byte-identical and a fallback build
# leaves the tree clean.
set -euo pipefail

VERSION="${1:-0.0.0-dev}"
VERSION="${VERSION#v}"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

cat > "$DIR/Sources/RheoclesCore/Version.generated.swift" <<SWIFT
// GENERATED by Scripts/generate-version.sh — do not edit, and do not commit a
// stamped value. The release build overwrites this from the tag; the committed
// value is the dev fallback a plain \`swift build\` reports.
enum GeneratedVersion {
    static let value = "$VERSION"
}
SWIFT
